[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
  from = "/faq"
  to = "/ways-to-help"
  status = 301

[[redirects]]
  from = "/create"
  to = "/postcards"
  status = 301

[[redirects]]
  from = "/lawsandsafety"
  to = "/laws-and-safety"
  status = 301

[[redirects]]
  from = "/register"
  to = "/add-a-group"
  status = 301
