backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Laws'
        name: 'laws'
        file: 'content/laws.md'
        fields:
          - { label: 'Header', name: 'header', widget: 'string' }
          - { label: 'Sub header', name: 'subheader', widget: 'string' }
          - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: 'Ways to help'
        name: 'ways-to-help'
        file: 'content/ways-to-help.md'
        fields:
          - { label: 'title', name: 'title', widget: 'string' }
          - { label: 'subtitle', name: 'subtitle', widget: 'string' }
          - label: 'questions'
            name: 'questions',
            widget: 'list'
            fields:
              - { label: 'hash', name: 'hash', widget: 'string' }
              - { label: 'Title', name: 'title', widget: 'string' }
              - { label: 'Body', name: 'body', widget: 'markdown' }
