backend:
  name: git-gateway
  branch: master
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - label: 'Laws'
        name: 'laws'
        file: 'content/laws.md'
        fields:
          - { label: 'Header', name: 'header', widget: 'string' }
          - { label: 'Sub header', name: 'subheader', widget: 'string' }
